export const projects = [
  {
    title: 'Finance ERP Application',
    description: "Developed and implemented a comprehensive Finance Module within an ERP system.The module was designed to streamline financial processes, enhance accuracy, and provide real-time insights for informed decision-making.",
    image: '/images/finance.png',
    tags: ["Angular,.NET,Postgresql,Bold Report,Syncfusion"],
    // visit: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    // source: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    id: 0,
  },
  {
    title: 'CRM Application',
    description: "Designed, developed, and implemented a comprehensive Customer Relationship Management (CRM) application from scratch. The CRM system aimed to streamline and enhance customer interactions, improve sales processes, and centralize customer data for more informed decision-making.",
    image: '/images/CRM.png',
    tags: ["Angular,.NET,Bootstrap,Postgresql"],
    // visit: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    // source: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    id: 1,
  },
  {
    title: 'HRMS Application',
    description: "Led the design, development, and implementation of a comprehensive Human Resource Management System (HRMS) application.The HRMS system aimed to streamline HR processes, enhance employee management, and improve overall workforce efficiency.",
    image: '/images/hrms.png',
    tags: ["Angular,.NET,Bootstrap,Primeng,Postgresql"],
    // visit: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    // source: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    id: 2,
  },
  {
    title: 'Ecommerce Application',
    description: "A fully functional Ecommerce application which comes with 3 modules Users,Admin and api.User can manage cart and order while admin can manage products and users and see statistics.",
    image: '/images/img6.png',
    tags: ["MERN,Redux,Stripe,Firebase,JWT"],
    visit: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    source: 'https://github.com/Sofiya-Mathew/MERN_ECOMMERCE.git',
    id: 3,
  },

  {
    title: 'YouTube clone app',
    description: "Utilized React, Node.js, Express,REdux,Firebase & MongoDB.User can upload videos like and dislike, comment and subscribe to channels.",
      image: '/images/1.png',
      tags: ["MERN,Redux,Firebase,JWT"],
    source: 'https://github.com/Sofiya-Mathew/youtube_full_stack.git',
    visit: 'https://github.com/Sofiya-Mathew/youtube_full_stack.git',
    id: 4,
  },
  {
    title: 'GPT3 Website',
    description: "A design based website of GPT3 which gives importance to modern UI UX design",
      image: '/images/img5.png',
      tags: ['REACT JS'],
    source: 'https://magical-kulfi-5f03e7.netlify.app/',
    visit: 'https://github.com/Sofiya-Mathew/GPT3_UI_UX_REACT.git',
    id: 5,
  },
  {
    title: 'Restaurant App',
    description:"A react app for displaying restaurants using rest API.",
    image: '/images/7.png',
    tags: ['REACT'],
    source: 'https://github.com/Sofiya-Mathew/REACT_Restaurant_App.git',
    visit: 'https://github.com/Sofiya-Mathew/REACT_Restaurant_App.git',
    id: 6,
  },
  {
    title: 'Bank App',
    description:"Users can register and login to the app.Users can deposit and withdraw from their accounts and see their transaction details.",
    image: '/images/2.png',
    tags: ['MEAN,JWT'],
    source: 'https://github.com/Sofiya-Mathew/MEAN_BANK_APP.git',
    visit: 'https://github.com/Sofiya-Mathew/MEAN_BANK_APP.git',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Higher Secondary, G.H.S.S Villadom, 84%', },
  { year: 2022, text: 'B TECH in Computer science, HGAE, 65%', },
  { year: 2022, text: 'Done MEARN stack development course,Luminar tecnolab', },
  { year: 2023, text: 'software Engineer,Thomsun Infocare', },
];